name: "Terraform Checks"

on:
  workflow_call:
    inputs:
      working_directory:
        required: false
        type: string
        default: '.'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform fmt
        id: fmt
        run: find . -path "./.terraform" -prune -o -name "*.tf" -exec dirname {} \; | sort -u | xargs -I {} sh -c 'cd "{}" && terraform fmt -check'
        working-directory: ${{ inputs.working_directory }}
      - uses: actions/github-script@v7
        if: ${{ failure() && github.event_name == 'pull_request' }}
        with:
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\``;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.32.0
        with:
          scan-type: 'config'
          severity: 'CRITICAL,HIGH'
          exit-code: 1